### ISSUE TITLE
Css Variables fallback

### ISSUE THREAD

**Issue by Jab2870** [less/less-plugin-autoprefix#32]
People are increasingly using css variables over less variables because of their inheritance abilities. 

Unfortunately, ie11.

It would be very helpful if this plugin were to add a version of the property if a fallback is specified. For example:

```less
@highlight: red;

::root {
--highlight: @highlight;
}

div{
--highlight: green;
}

a{
color: var(--highlight, @highlight)
}
```

Currently, the above compiles to:

```css
::root {
  --highlight: red;
}
div {
  --highlight: green;
}
a {
  color: var(--highlight, red);
}
```

This would result in anchors being red in most cases. For browsers that support variables, anchors would be green if inside a div. 

In a browser that doesn't support variables, anchors will be the default anchor colour.

My question is this:

Would it be possible for auto-prefix to turn `color: var(--highlight, @highlight)` into

```less
color: @highlight;
color: var(--highlight, @highlight);
```

**Comment by seven-phases-max** [comment]
1. The plugin has no idea of Less variables (basically the plugin is a wrapped over 
2. And even if it, what you want is still impossible simply because Less has no idea of your HTML hierarchy (note Less code is compiled to a CSS with no knowledge what page you'll later apply this CSS to). E.g. consider the following snippet:
CSS:
```css
div  {--highlight: green}
span {--highlight: blue}
a {color: var(--highlight)}
```
HTML:
```html
<div ><a>Foo</a></div>
<span><a>Bar</a></span>
```
Now how Less can possibly know if the fallback value is `blue` or `green`?. There's no way.
